In [ ]:
#### 시리즈 - 1차원

#### 데이터프레임?
# - 2차원 표 형태의 자료구조로, 행과 열로 구성되어 있습니다. 
# - 각 열은 서로 다른 데이터 유형을 가질 수 있으며, 각 행은 관측값을 나타냅니다. 
# - 데이터프레임은 판다스 라이브러리에서 제공하는 주요 자료구조 중 하나로, 
# - 데이터를 효율적으로 저장하고 조작할 수 있도록 설계되었습니다.
# - 데이터프레임은 다양한 데이터 분석 작업에 사용되며, 
# - 데이터 정제, 변환, 시각화 등 다양한 기능을 제공합니다. 
# - 데이터프레임을 사용하면 데이터를 쉽게 필터링, 그룹화, 집계할 수 있으며, 
# - 다양한 통계적 분석과 머신러닝 모델링에도 활용됩니다. 
# - 데이터프레임은 특히 대규모 데이터셋을 다룰 때 유용하며, 
# - 데이터 과학자와 분석가들에게 널리 사용되는 도구입니다.

In [ ]:
# pip install -U jupyter ipykernel notebook
# pip install pandas
# 실행이 안되면 커널을 다시시작

In [1]:
import pandas as pd

# 딕셔너리 자료를 data 객체에 저장
data = {'name': ['Mark', 'Jane', 'Chris', 'Ryan'],
        'age': [33, 32, 44, 42],
        'score': [91.3, 83.4, 77.5, 87.7]}

print(data)

{'name': ['Mark', 'Jane', 'Chris', 'Ryan'], 'age': [33, 32, 44, 42], 'score': [91.3, 83.4, 77.5, 87.7]}

In [3]:
# DataFrame() 함수로 data 객체를 데이터프레임으로 만들어 df 객체에 저장
df = pd.DataFrame(data)
df

    name  age  score
0   Mark   33   91.3
1   Jane   32   83.4
2  Chris   44   77.5
3   Ryan   42   87.7

In [4]:
# 합계
print(df.sum())

name     MarkJaneChrisRyan
age                    151
score                339.9
dtype: object

In [6]:
# df → DataFrame 객체
# .mean() → 평균 계산
# numeric_only=True → 숫자 데이터만 사용
# print(df.mean()) -> 에러
print(df.mean(numeric_only=True))

age      37.750
score    84.975
dtype: float64

In [7]:
# 데이터 선택하기
print(df.age)
print(df['age'])

0    33
1    32
2    44
3    42
Name: age, dtype: int64
0    33
1    32
2    44
3    42
Name: age, dtype: int64

In [8]:
import re, os
os.chdir(r'E:\wi\git\py0811\p05')

In [10]:
# 판다스로 CSV 파일 읽기
# read_csv() → CSV 파일 읽기
# thousands=','
# → 1,000, 25,300 같은 값을 숫자로 변환
df = pd.read_csv('apt2308.csv', thousands=',')
# df = pd.read_csv('apt2308.csv', encoding='utf8', thousands=',')
# df = pd.read_csv('apt2308.csv', encoding='utf-8', thousands=',')
df

,시군구,번지,본번,부번,단지명,전용면적,계약년월,계약일,거래금액,층,건축년도,도로명,해제사유발생일,등기신청일자,거래유형,중개사소재지
0,강원특별자치도 강릉시 견소동,202,202,0,송정한신,59.800,202308,8,23000,9,1997.0,경강로2539번길 8,NaN,,중개거래,강릉시
1,강원특별자치도 강릉시 견소동,202,202,0,송정한신,84.945,202308,14,31000,13,1997.0,경강로2539번길 8,NaN,,중개거래,강릉시
2,강원특별자치도 강릉시 견소동,202,202,0,송정한신,43.380,202308,30,16400,10,1997.0,경강로2539번길 8,NaN,,중개거래,강릉시
3,강원특별자치도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,59.990,202308,19,24500,5,2005.0,경강로2539번길 23,NaN,,중개거래,강릉시
4,강원특별자치도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,84.990,202308,22,28500,4,2005.0,경강로2539번길 22,NaN,,중개거래,강릉시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26504,충청북도 충주시 호암동,1063,1063,0,충주호암두진하트리움아파트,66.957,202308,16,34100,15,2019.0,호암수청2로 78,NaN,,중개거래,충북 충주시
26505,충청북도 충주시 호암동,1063,1063,0,충주호암두진하트리움아파트,84.803,202308,19,41000,12,2019.0,호암수청2로 78,NaN,,중개거래,충북 충주시
26506,충청북도 충주시 호암동,547-6,547,6,호반현대,84.960,202308,12,15700,2,1994.0,신촌2길 29,NaN,,중개거래,충북 충주시
26507,충청북도 충주시 호암동,221-1,221,1,호암리버빌(2단지),84.680,202308,10,20700,3,2002.0,호암중앙2로 5,NaN,,중개거래,충북 충주시
26508,충청북도 충주시 호암동,1191,1191,0,호암힐데스하임,84.950,202308,21,40200,11,2019.0,호암토성2로 1,NaN,,중개거래,충북 충주시

In [11]:
# 26509개의 자료가 들어있다.
print(len(df))

26509